services:
  - type: web
    name: alpha-bank-pay
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /ping

    envVars:
      - key: APP_URL
        sync: false

      # ——— Telegram ———
      - key: CLIENT_BOT_TOKEN
        sync: false
      - key: ADMIN_BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false

      # ——— Painel ———
      - key: PANEL_PASSWORD
        sync: false

      # ——— PodPay ———
      - key: PODPAY_API_KEY
        sync: false
      - key: PODPAY_POSTBACK_URL
        sync: false

      # ——— XPayTech ———
      - key: XPAYTECH_USERNAME
        sync: false
      - key: XPAYTECH_PASSWORD
        sync: false
      - key: XPAYTECH_WEBHOOK_URL
        sync: false

      # ——— Servidor ———
      - key: PORT
        value: "3000"

      # ——— Cloud Backup (OPCIONAL) ———
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: TELEGRAM_STORAGE_CHANNEL
        sync: false
